---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAi6arE9XkQBr1yLtQhL3kjtlYY6gIh5jwp0x9kuR53ZrZC+KxynehR1G7kKHBY0qB7bGCJ0+Q6MtTxo2vKvavnYjlGOrhn3ob0+E7hiyL4Z7wpyJDblCoc/Uvmqri6eIyNUEcLPi6PpUY11+5YxlpMvfdcOQqpLX/bZ+m2pFrmuz0q7k1mlnGJ+cY6Yz4VocJAHv5YA1g/G3raZ+grPn0TpslOYI+akBOosVu2HchFQSSbHrfa0B0/Pj601zleXIKXPgwoKMkxx5YE2awoddbtX8hyyf6CyQfYkSTUsMrcWB9yueccfnaXWpcM6Br7PUGD8xC8ziMOfYAA0Sv4VGs5pXPLRt5DNeukBhsRghqflpxuussQYdppxDx8P5Sxm6ODUXDzr6iNBWq1UlozsfGfD6Ry+68wlmdRdWsx52VgzDVUzSGFjnHhAmtVxvAM4SOTGcOa2CWMUiRBY7mLzN29Fb6VphqdcrMq810Midpzdyf60hRKr5OlQ3uuPKj/IbGPQ2SE0qdD07gLhOKIu94HUSJT8QwFAz53VKBIRdC1wdKyFXJKgAH2AI2VCvuOhJgpNGFY8LCeG4mB0IuV38bCaDdS2aQlAlh0HmeHhQKZnOdkdUGIa29T0WQh4/O2gd6CQpqj4b5V7cNS8lC/xBGMIUtZgqQXaLDUOXr2CpFWrXWYSAHT+CI0gU/YUSNxHla14YAuVEuB5pD2kWbXbfdreT6NTMA9rfw=
    nextcloud-username: AgBOR+XoWrjn3OS4Ubv73rOBkAaf2O1K4Dvgw6TtapQVAoSDBDCI0/xnZCUaF0wbMALZBMCzcPuIZcmslY6TrB4mdHCjzmOG1TD8P6xFZ8dyb4wWKWoRaEBAZINHynRhMS7HuKM3GBSpzl8IFTN0guyowdd5o1z9XONIQ1DEQaLZ6J943zbkOLtvoZMBchi2vB6ora8ADDSzMLUhywibEnRWo9x/rDruNSvn2vbgAsQWeb4jnRoWCXO6QBEY3EF1+7bSWyIPchOAOIf9iy4xR85XiPsdij90F9Suaf3fQB/3gfbvz6kaGnSjAwfEc3QVH0vzJn7RMwsvF/SL9aMFOAuCXJaUeYxMZN2lH3KEIjUkk/zXnpiIBKi5wu6xvfmu16W66e/0f3U93p71iwjr0BPWkbaRNwlS/jcxbPjySe0A1icAVxbGAS9OIm6QTpk5c/MxZdqE1IPtParhnkZdMNhoAxL1h4vtZ0dXY0hBJ4i4fNcunmY5YBcipDF+THUdMTZ7RNfMKVMSFsJ1T1MmUhRXL77yjpDSq7E8VtnL+GLJ6ZHNxQDNN6eUnAqGUl1MyO7xS/SUQidDWoTFVMUxN0h0ZJ6XJCRNbzhT35p2/SfAYJVl63fJlHbI+GTdIa3JoiyJFXr7zLWhO46PSDbDtQDJDChjM4CmX9vfdmhXbDqlTHKKOAfxOuy62R3qyaHoGMrluJNQvg==
  template:
    metadata:
      name: nextcloud-admin
      namespace: nextcloud
